#!/bin/sh
set -eu

build_dir=$(mktemp -d /tmp/algobridge0017-public-build.XXXXXX)
trap 'rm -rf "$build_dir"' EXIT HUP INT TERM

cmake -S /testbed -B "$build_dir" -G Ninja \
  -DGMX_FFT_LIBRARY=fftpack -DGMX_SIMD=SSE2 \
  -DGMX_MPI=OFF -DGMX_THREAD_MPI=OFF -DGMX_OPENMP=OFF -DGMX_GPU=OFF \
  -DBUILD_TESTING=OFF -DGMX_BUILD_UNITTESTS=OFF -DGMXAPI=OFF \
  -DGMX_INSTALL_NBLIB_API=OFF -DGMX_BUILD_MANUAL=OFF \
  -DGMX_EXTERNAL_BLAS=OFF -DGMX_EXTERNAL_LAPACK=OFF \
  -DCMAKE_BUILD_TYPE=Release
cmake --build "$build_dir" --target gmx -j8
CANDIDATE_GMX="$build_dir/bin/gmx" python3 /examples/verify_examples.py
